### ISSUE TITLE
Units of gdf

### ISSUE THREAD

**Issue by peterlevy** [ilapros/rnrfa#10]
The function documentation says "Gauged Daily Flow is measured in m^3/day".
However, Gauged Daily Flow is given in m^3/sec in the data accessible via the NRFA web site (https://nrfa.ceh.ac.uk/gauged-daily-flow-data), so unless there is a conversion done which I missed, the documentation needs correcting.

**Comment by ilapros** [comment]
Hi Peter - 
Yes indeed - good catch, I have fixed that and a few other things in the documentation. 
Thanks
